const nome = prompt("Digite seu nome conpleto:");
document.body.innerHTML += `O seu nome é: <strong>${nome}</strong> <br>`;
document.body.innerHTML += `Seu nome tem ${nome.length} letras <br>`;
document.body.innerHTML += `A segunda letra do seu nome e: ${nome.charAt(1)} <br>`;
document.body.innerHTML += `Qual o primeiro indice da letra 'a'no seu nome? ${nome.indexOf('a')} <br>`;
document.body.innerHTML += `As ultimes 3 letras do seu nome são: ${nome.slice(-3)} <br>`;
document.body.innerHTML += `As palavras do seu nome são: ${nome.split(' ')} <br>`;
document.body.innerHTML += `Seu nome com letras  maiusculas: ${nome.toUpperCase()} <br>`;
document.body.innerHTML +=  `Seu nome co letras minusculas: ${nome.toLowerCase()} <br>`;
